[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.4",
    "opencv-python>=4.10.0.84",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pyautogui>=0.9.54",
    "pytelegrambotapi>=4.29.1",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.48",
]
